name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Use Node.js 18.18.1
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.18.1"
      - name: Install yarn and run unittest
        run: |
          yarn
          yarn test
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
        name: owner/repository/image
          # username: ${{ github.actor }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          # name: myDocker/repository
          # username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.DOCKER_PASSWORD }}
          # name: zkadish/create-react-app-github-actions/
          # registry: https://ghcr.io
          # username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.GITHUB_TOKEN }}
          # dockerfile: Dockerfile-prod
          # tags: cra-test
