name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Use Node.js 18.18.1
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.18.1"
      - name: Install yarn and run unittest
        run: |
          yarn
          yarn test
        env:
          CI: true
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: zkadish/create-react-app-github-actions/cra-test-github
          # username: ${{ github.actor }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: Dockerfile-prod
          tags: cra-test
  # deploy-api-1:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
      - name: Deploy api to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.0
        # with:
          host: ${{ secrets.DO_API1_HOST }}
        #   username: root
        #   key: ${{ secrets.DO_API_KEY }}
        #   port: 22
          username: root
          key: ${{ secrets.DO_API_KEY }}
          port: 22
          script: |
            # doctl registry login --expiry-seconds 180
            docker pull docker.pkg.github.com/zkadish/create-react-app-github-actions/cra-test-github:latest

            echo "calling shutdown endpoint..."
            curl --silent http://localhost/shutdown || true

            echo "giving healthcheck time to fail..."
            sleep 30 # ((unhealthy + 1) * interval)

            docker stop api || true
            docker rm api || true

            echo "starting server instance..."
            docker run -d \
              --restart always \
              -p 0.0.0.0:80:80 \
              --name api \
              registry.digitalocean.com/<REGISTRY_NAME>/api:latest

            echo "giving healthcheck time to recover..."
            sleep 40 # ((healthy + 1) * interval)

            curl --silent --fail http://localhost/health
